<template>
  <main class="min-h-svh w-full bg-slate-100 text-slate-950">
    <div v-if="orderStore.errorMsg || order?.expired" class="mx-auto grid min-h-screen max-w-md place-items-center p-6 text-center"><div><div class="mx-auto grid h-16 w-16 place-items-center rounded-full bg-slate-200"><ShieldCheck class="h-8 w-8" /></div><h1 class="mt-5 text-xl font-black">Отслеживание завершено</h1><p class="mt-2 text-sm text-slate-600">Вызов завершён или ссылка больше не действует.</p><a href="tel:103" class="mt-5 flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-950 text-sm font-black text-white"><Phone class="h-4 w-4" /> Позвонить диспетчеру</a></div></div>
    <div v-else-if="!order" class="grid min-h-screen place-items-center text-center" role="status"><div><LoaderCircle class="mx-auto h-9 w-9 animate-spin text-teal-700" /><p class="mt-3 text-sm font-bold">Получаем информацию о бригаде…</p></div></div>

    <template v-else>
      <div class="fixed inset-0 z-0"><LiveMap :ambulance-loc="order.currentLoc" :destination-loc="order.destinationLoc" :route-path="order.routePath" /></div>
      <header class="fixed inset-x-3 top-3 z-[600] mx-auto max-w-md rounded-2xl border border-slate-200 bg-white/95 shadow-lg backdrop-blur"><div class="flex h-16 items-center justify-between px-4"><div class="flex min-w-0 items-center gap-3"><div class="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-teal-800 text-white"><Ambulance class="h-5 w-5" /></div><div class="min-w-0"><h1 class="text-sm font-black">MedTracker</h1><p class="truncate text-xs font-semibold text-slate-500">{{ order.carNumber }}</p></div></div><div class="flex items-center gap-1.5"><button class="hidden h-10 w-10 place-items-center rounded-lg bg-slate-100 min-[390px]:grid" aria-label="Поделиться" @click="shareWithFamily"><Share2 class="h-4 w-4" /></button><ThemeToggle /><LanguageSwitcher /></div></div></header>
      <div class="fixed inset-x-0 bottom-0 z-20 mx-auto flex w-full max-w-md flex-col overflow-hidden rounded-t-[28px] border-x border-t border-slate-200 bg-slate-100 shadow-2xl transition-[height] duration-300 ease-out" :class="isSheetExpanded?'h-[88svh]':'h-[30svh]'">
        <button type="button" class="sticky top-0 z-10 flex min-h-11 shrink-0 flex-col items-center justify-center border-b border-slate-200 bg-white/95 backdrop-blur" :aria-expanded="isSheetExpanded" aria-label="Развернуть или свернуть информацию" @click="isSheetExpanded=!isSheetExpanded"><span class="h-1 w-10 rounded-full bg-slate-300"></span><span class="mt-1 text-[10px] font-bold text-slate-500">{{ isSheetExpanded?'Свернуть':'Показать подробности' }}</span></button>
        <div class="flex-1 space-y-3 overflow-y-auto overscroll-contain p-3 pb-[max(2rem,env(safe-area-inset-bottom))]">
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <div class="flex items-center justify-between gap-2"><span class="rounded-md px-2.5 py-1 text-[11px] font-black" :class="statusClass">{{ statusText }}</span><span class="text-[10px] font-bold" :class="gpsIsStale?'text-amber-700':'text-slate-500'">{{ gpsFreshness }}</span></div>
          <div class="mt-5 text-center"><template v-if="order.status==='EN_ROUTE'"><p class="text-4xl font-black text-teal-900">{{ etaRange }}</p><p class="mt-1 text-xs font-bold uppercase tracking-wide text-slate-500">ориентировочно до прибытия</p></template><template v-else><component :is="heroIcon" class="mx-auto h-9 w-9 text-teal-800" /><h2 class="mt-2 text-xl font-black">{{ heroTitle }}</h2><p class="mt-1 text-sm text-slate-500">{{ heroDescription }}</p></template></div>
          <div class="mt-5 grid grid-cols-4 gap-1"><div v-for="(step,index) in steps" :key="step" class="text-center"><div class="h-1.5 rounded-full" :class="currentStep>=index?'bg-teal-700':'bg-slate-200'"></div><span class="mt-1.5 block text-[9px] font-bold" :class="currentStep>=index?'text-teal-800':'text-slate-400'">{{ step }}</span></div></div>
          <div v-if="gpsIsStale&&order.status==='EN_ROUTE'" class="mt-4 flex gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-900" role="status"><WifiOff class="h-4 w-4 shrink-0" /><span><strong>Координаты временно не обновляются.</strong> Расчёт времени может быть неточным.</span></div>
        </section>
        <a href="tel:+77778887766" class="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-slate-950 text-xs font-black text-white"><Phone class="h-4 w-4" /> Позвонить диспетчеру</a>
        <PatientActionAccordions :order="order" @update-access="onUpdateAccess" @update-symptoms="onUpdateSymptoms" />
        </div>
      </div>
    </template>
  </main>
</template>

<script setup lang="ts">
import PatientActionAccordions from '@/components/PatientActionAccordions.vue';
import ThemeToggle from '@/components/ui/ThemeToggle.vue';
import { computed,onBeforeUnmount,onMounted,ref } from 'vue'; import { useRoute } from 'vue-router'; import { useOrderStore } from '@/stores/orderStore'; import LiveMap from '@/components/LiveMap.vue'; import AccessForm from '@/components/AccessForm.vue'; import SymptomSelector from '@/components/SymptomSelector.vue'; import PreArrivalChecklist from '@/components/PreArrivalChecklist.vue'; import LanguageSwitcher from '@/components/ui/LanguageSwitcher.vue'; import { Ambulance,CheckCircle2,ChevronDown,ClipboardCheck,HeartPulse,KeyRound,LoaderCircle,MapPinCheck,Phone,Share2,ShieldCheck,Stethoscope,WifiOff } from 'lucide-vue-next'; import type { AccessInfo,OrderStatus } from '@/types';
const route=useRoute(),orderStore=useOrderStore(),token=(route.params.token as string)||''; const openPanels=ref(new Set<string>()),isSheetExpanded=ref(false),isWorseDialogOpen=ref(false),now=ref(Date.now()); let timer=0; const order=computed(()=>orderStore.currentOrder?.token===token?orderStore.currentOrder:null); onMounted(()=>{orderStore.joinOrderRoom(token);timer=window.setInterval(()=>now.value=Date.now(),10000)});onBeforeUnmount(()=>clearInterval(timer));
function togglePanel(key:string){const next=new Set(openPanels.value);if(next.has(key))next.delete(key);else next.add(key);openPanels.value=next;}
const labels:Record<OrderStatus,string>={ACCEPTED:'Вызов принят',EN_ROUTE:'Бригада в пути',ARRIVED:'Бригада прибыла',HOSPITAL_TRANSPORT:'Транспортировка',COMPLETED:'Вызов завершён'};const statusText=computed(()=>order.value?labels[order.value.status]:'');const statusClass=computed(()=>order.value?.status==='EN_ROUTE'||order.value?.status==='ARRIVED'?'bg-teal-100 text-teal-800':'bg-slate-100 text-slate-700');const steps=['Принят','В пути','Прибыл','В клинику'];const currentStep=computed(()=>order.value?Math.min(3,Math.max(0,['ACCEPTED','EN_ROUTE','ARRIVED','HOSPITAL_TRANSPORT','COMPLETED'].indexOf(order.value.status))):0);
const distance=computed(()=>{if(!order.value)return null;const a=order.value.currentLoc,d=order.value.destinationLoc;if(!a||!d)return null;const lat=(d.lat-a.lat)*111,lng=(d.lng-a.lng)*111*Math.cos(a.lat*Math.PI/180);return Math.sqrt(lat*lat+lng*lng)});const etaRange=computed(()=>{const eta=order.value?.etaMinutes||(distance.value===null?null:Math.max(2,Math.ceil(distance.value*2.5)));return eta?`${Math.max(1,eta-2)}–${eta+3} мин`:'Время уточняется'});const age=computed(()=>orderStore.lastLocationUpdate?Math.floor((now.value-orderStore.lastLocationUpdate)/1000):null);const gpsIsStale=computed(()=>age.value===null||age.value>60);const gpsFreshness=computed(()=>age.value===null?'GPS уточняется':age.value<10?'GPS обновлён сейчас':age.value<60?`GPS обновлён ${age.value} сек назад`:`GPS обновлялся ${Math.floor(age.value/60)} мин назад`);
const heroTitle=computed(()=>order.value?.status==='ARRIVED'?'Бригада уже на месте':order.value?.status==='HOSPITAL_TRANSPORT'?'Пациент едет в клинику':'Вызов принят');const heroDescription=computed(()=>order.value?.status==='ARRIVED'?'Проверьте, открыт ли вход для врачей':order.value?.status==='HOSPITAL_TRANSPORT'?'Отслеживание маршрута продолжается':'Бригада готовится к выезду');const heroIcon=computed(()=>order.value?.status==='ARRIVED'?MapPinCheck:CheckCircle2);const panels=[{key:'access',title:'Уточнить доступ',icon:KeyRound,color:'bg-teal-50 text-teal-800'},{key:'symptoms',title:'Передать симптомы',icon:Stethoscope,color:'bg-rose-50 text-rose-700'},{key:'ready',title:'Подготовиться к приезду',icon:ClipboardCheck,color:'bg-amber-50 text-amber-700'}];const onUpdateAccess=(v:Partial<AccessInfo>)=>orderStore.updateAccessInfo(token,v);const onUpdateSymptoms=(v:string[])=>orderStore.updateSymptoms(token,v);async function shareWithFamily(){const url=location.href;if(navigator.share)await navigator.share({title:'Отслеживание скорой помощи',url});else window.open(`https://wa.me/?text=${encodeURIComponent(url)}`,'_blank')}
</script>

<style scoped>
@media (min-width: 768px) {
  header { max-width: 42rem; }
  main > div.fixed.inset-x-0.bottom-0 { max-width: 42rem; }
}
</style>
